// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClkQFr__odcfiJJqKvVt4qlRjlotjDEgA',
    appId: '1:51280083574:web:b54d6e1a0345151345bd57',
    messagingSenderId: '51280083574',
    projectId: 'flutter-123-3204d',
    authDomain: 'flutter-123-3204d.firebaseapp.com',
    storageBucket: 'flutter-123-3204d.firebasestorage.app',
    measurementId: 'G-79834YSENL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyvdOiGCsM1Ep6NYe1Rhy07QX5LElu5DI',
    appId: '1:51280083574:android:a4866afd1c86948a45bd57',
    messagingSenderId: '51280083574',
    projectId: 'flutter-123-3204d',
    storageBucket: 'flutter-123-3204d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVHZtQZuJu1dltJYVLYFuGgB-GWU63uE',
    appId: '1:51280083574:ios:9a8e5aa646e8e42345bd57',
    messagingSenderId: '51280083574',
    projectId: 'flutter-123-3204d',
    storageBucket: 'flutter-123-3204d.firebasestorage.app',
    androidClientId: '51280083574-c8rvo1i32ulonc7ml52jtsf8ngca2trf.apps.googleusercontent.com',
    iosClientId: '51280083574-34gvesdlqftr11m03m35rg5hh3uf0sth.apps.googleusercontent.com',
    iosBundleId: 'com.example.osmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVHZtQZuJu1dltJYVLYFuGgB-GWU63uE',
    appId: '1:51280083574:ios:9a8e5aa646e8e42345bd57',
    messagingSenderId: '51280083574',
    projectId: 'flutter-123-3204d',
    storageBucket: 'flutter-123-3204d.firebasestorage.app',
    androidClientId: '51280083574-c8rvo1i32ulonc7ml52jtsf8ngca2trf.apps.googleusercontent.com',
    iosClientId: '51280083574-34gvesdlqftr11m03m35rg5hh3uf0sth.apps.googleusercontent.com',
    iosBundleId: 'com.example.osmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClkQFr__odcfiJJqKvVt4qlRjlotjDEgA',
    appId: '1:51280083574:web:7cd3312fe648c5c545bd57',
    messagingSenderId: '51280083574',
    projectId: 'flutter-123-3204d',
    authDomain: 'flutter-123-3204d.firebaseapp.com',
    storageBucket: 'flutter-123-3204d.firebasestorage.app',
    measurementId: 'G-KZRHBKC6NH',
  );
}
